name: Scheduler
on:
  schedule:
    # Runs every Friday @ 17:15
    - cron:  '15 17 * * 5'
jobs: 
  graduate-packages: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Graduate packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          npm ci
          npm run bootstrap
          npm run build
          npm run test
          npm run version:graduate -- --yes || echo "Nothing to graduate"
          npm run build
          npm run publish -- --yes || echo "Nothing to publish"
